Styling branch
zsolt270/diligent-academy-react-ts2 pull request #2
Opened 2024-11-01 20:14 UTC by zsolt270

Főztem egy kinézetet az appnak és hozzá feltelepítettem a react-iconst is, amit a delete gombnál használtam. 
Kérlek majd írjátok meg hogy jó-e vagy odaégettem-e.

2024-11-02 18:41 UTC, francisco-kpodotay requested changes
Overall, your code is well-written! However, the large indentation spaces make it a bit difficult to read. I know this isn't necessarily your fault, but it's been an interesting experience to navigate through. Keep up the good work!

2024-11-02 18:41 UTC, francisco-kpodotay commented on src/components/Main.tsx
Removed the unnecessary addBtnShowed state for cleaner code. Replaced it with a direct conditional rendering check on line 60:
```tsx
{todoText && (
```

2024-11-02 19:25 UTC, zsolt270 commented on src/components/Main.tsx
I cant see your changes, for me there is still:

{addBtnShowed && ( on line 60.

2024-11-03 11:38 UTC, francisco-kpodotay commented on src/components/Main.tsx
Yes, I didn't modify your code directly. I requested changes on your pull request instead, as I suggested removing the ```addBtnShowed``` state for cleaner code. You’ll need to refactor your code accordingly.

2024-11-03 12:46 UTC, zsolt270 commented on src/components/Main.tsx
Ok, I just assumed that u already made the changes because u commented that "Removed the unnecessary addBtnShowed state" and "Replaced it". But then yes im going to change it.

2024-11-03 12:52 UTC, francisco-kpodotay commented on src/components/Main.tsx
Oh, I see now—my comment was misleading. I’m really sorry for the confusion! 😞

2024-11-06 10:37 UTC, zsolt270 commented on src/components/Main.tsx
I added the requested changes to the file. Also I re-requested a review for it.

2024-11-06 10:52 UTC, francisco-kpodotay approved these changes
Nice work!

2024-11-06 10:52 UTC, merged